version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t docker1 .
      - docker tag docker1:latest 911870334818.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/docker1:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 911870334818.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/docker1:latest
